from fastapi import APIRouter, HTTPException
from database.config import HousePriceInfo_table, database

import numpy as np
import joblib

from models.price_predict import PriceInputData

router = APIRouter() 

model = joblib.load("ml_models/House_price_prediction_model.model")

@router.post("/house_price_predictor", status_code=201)
async def predict_price(data: PriceInputData):
    title_map = {"Block of Flats":0,"Detached Bungalow":1,"Detached Duplex":2,"Semi Detached Bungalow":3,"Semi Detached Duplex":4,"Terraced Bungalow":5,"Terraced Duplexes":6}
    town_map = {'Aba':0,
'Abeokuta North':1,
'Abeokuta South':2,
'Abraka':3,
'Ado-Ekiti':4,
'Ado-Odo/Ota':5,
'Afijio':6,
'Agbara-Igbesa':7,
'Agege':8,
'Ajah':9,
'Akinyele':10,
'Akure':11,
'Alimosho':12,
'Amuwo Odofin':13,
'Apapa':14,
'Apo':15,
'Arepo':16,
'Asaba':17,
'Asokoro District':18,
'Ayobo':19,
'Badagry':20,
'Bwari':21,
'Central Business District':22,
'Chikun':23,
'Dakibiyu':24,
'Dakwo':25,
'Dape':26,
'Dekina':27,
'Diplomatic Zones':28,
'Duboyi':29,
'Durumi':30,
'Egbe':31,
'Egor':32,
'Ejigbo':33,
'Eleme':34,
'Enugu':35,
'Epe':36,
'Ewekoro':37,
'Gaduwa':38,
'Galadimawa':39,
'Garki':40,
'Gbagada':41,
'Gudu':42,
'Guzamala':43,
'Guzape District':44,
'Gwagwalada':45,
'Gwarinpa':46,
'Ibadan':47,
'Ibadan North':48,
'Ibadan North-East':49,
'Ibadan North-West':50,
'Ibadan South-West':51,
'Ibafo':52,
'Ibeju Lekki':53,
'Idimu':54,
'Ido':55,
'Idu Industrial':56,
'Ifako-Ijaiye':57,
'Ifo':58,
'Ijaiye':59,
'Ijebu Ode':60,
'Ijesha':61,
'Ijoko':62,
'Ikeja':63,
'Ikorodu':64,
'Ikot Ekpene':65,
'Ikotun':66,
'Ikoyi':67,
'Ilorin East':68,
'Ilorin West':69,
'Ilupeju':70,
'Ipaja':71,
'Isheri':72,
'Isheri North':73,
'Isolo':74,
'Jabi':75,
'Jahi':76,
'Kabusa':77,
'Kado':78,
'Kaduna North':79,
'Kaduna South':80,
'Kafe':81,
'Karmo':82,
'Karsana':83,
'Karu':84,
'Katampe':85,
'Kaura':86,
'Keffi':87,
'Ketu':88,
'Kosofe':89,
'Kubwa':90,
'Kuje':91,
'Kukwaba':92,
'Kurudu':93,
'Lagos Island':94,
'Lekki':95,
'Life Camp':96,
'Lokogoma District':97,
'Lugbe District':98,
'Mabushi':99,
'Magboro':100,
'Magodo':101,
'Maitama District':102,
'Maryland':103,
'Mbora (Nbora)':104,
'Mowe Ofada':105,
'Mowe Town':106,
'Mpape':107,
'Mushin':108,
'Obio-Akpor':109,
'Ogudu':110,
'Ojo':111,
'Ojodu':112,
'Ojota':113,
'Oke-Aro':114,
'Okene':115,
'Oluyole':116,
'Oredo':117,
'Orozo':118,
'Oshodi':119,
'Osogbo':120,
'Owerri Municipal':121,
'Owerri North':122,
'Owerri West':123,
'Paikoro':124,
'Port Harcourt':125,
'Sango Ota':126,
'Shomolu':127,
'Simawa':128,
'Surulere':129,
'Udu':130,
'Ughelli South':131,
'Uhunmwonde':132,
'Umuahia':133,
'Utako':134,
'Uyo':135,
'Victoria Island (VI)':136,
'Warri':137,
'Wumba':138,
'Wuse':139,
'Wuse 2':140,
'Wuye':141,
'Yaba':142,
'Yenagoa':143,}
    state_map = {'Abia':0,
'Abuja':1,
'Akwa Ibom':2,
'Anambara':3,
'Bayelsa':4,
'Borno':5,
'Delta':6,
'Edo':7,
'Ekiti':8,
'Enugu':9,
'Imo':10,
'Kaduna':11,
'Kogi':12,
'Kwara':13,
'Lagos':14,
'Nasarawa':15,
'Niger':16,
'Ogun':17,
'Osun':18,
'Oyo':19,
'Rivers':20,}
    if data.town not in town_map or data.state not in state_map or data.title not in title_map:
        raise HTTPException(status_code=400, detail="Invalid town or state or title value")
    town_encoded = town_map[data.town]
    state_encoded = state_map[data.state]
    title_encoded = title_map[data.title]

    input_array = np.array([[
    data.bedrooms,
    data.bathrooms,
    data.toilets,
    data.parking_space,
    title_encoded,
    town_encoded,
    state_encoded
    ]])
    prediction = model.predict(input_array)
    output = prediction.tolist()[0]
    def decode_title(encoded_title: int) -> str:
        reverse_title_map = {v: k for k, v in title_map.items()}
        return reverse_title_map.get(encoded_title, "Unknown Title")
    def decode_town(encoded_town: int) -> str:
        reverse_town_map = {v: k for k, v in town_map.items()}
        return reverse_town_map.get(encoded_town, "Unknown Town")
    def decode_state(encoded_state: int) -> str:    
        reverse_state_map = {v: k for k, v in state_map.items()}
        return reverse_state_map.get(encoded_state, "Unknown State")
    

    query = HousePriceInfo_table.insert().values(bedroom=data.bedrooms, bathroom=data.bathrooms, toilets=data.toilets, parking_space=data.parking_space, title=decode_title(title_encoded), town = decode_town(town_encoded), state=decode_state(state_encoded))
    await database.execute(query)
    return {
        "price": output,
        "message": f"The price range for the house is between {output-5950} and {output+5970}"
    }
    

# @router.get("/naaa")
# async def home():
#     town_map = {'Aba':0,
# 'Abeokuta North':1,
# 'Abeokuta South':2,
# 'Abraka':3,
# 'Ado-Ekiti':4,
# 'Ado-Odo/Ota':5,
# 'Afijio':6,
# 'Agbara-Igbesa':7,
# 'Agege':8,
# 'Ajah':9,
# 'Akinyele':10,
# 'Akure':11,
# 'Alimosho':12,
# 'Amuwo Odofin':13,
# 'Apapa':14,
# 'Apo':15,
# 'Arepo':16,
# 'Asaba':17,
# 'Asokoro District':18,
# 'Ayobo':19,
# 'Badagry':20,
# 'Bwari':21,
# 'Central Business District':22,
# 'Chikun':23,
# 'Dakibiyu':24,
# 'Dakwo':25,
# 'Dape':26,
# 'Dekina':27,
# 'Diplomatic Zones':28,
# 'Duboyi':29,
# 'Durumi':30,
# 'Egbe':31,
# 'Egor':32,
# 'Ejigbo':33,
# 'Eleme':34,
# 'Enugu':35,
# 'Epe':36,
# 'Ewekoro':37,
# 'Gaduwa':38,
# 'Galadimawa':39,
# 'Garki':40,
# 'Gbagada':41,
# 'Gudu':42,
# 'Guzamala':43,
# 'Guzape District':44,
# 'Gwagwalada':45,
# 'Gwarinpa':46,
# 'Ibadan':47,
# 'Ibadan North':48,
# 'Ibadan North-East':49,
# 'Ibadan North-West':50,
# 'Ibadan South-West':51,
# 'Ibafo':52,
# 'Ibeju Lekki':53,
# 'Idimu':54,
# 'Ido':55,
# 'Idu Industrial':56,
# 'Ifako-Ijaiye':57,
# 'Ifo':58,
# 'Ijaiye':59,
# 'Ijebu Ode':60,
# 'Ijesha':61,
# 'Ijoko':62,
# 'Ikeja':63,
# 'Ikorodu':64,
# 'Ikot Ekpene':65,
# 'Ikotun':66,
# 'Ikoyi':67,
# 'Ilorin East':68,
# 'Ilorin West':69,
# 'Ilupeju':70,
# 'Ipaja':71,
# 'Isheri':72,
# 'Isheri North':73,
# 'Isolo':74,
# 'Jabi':75,
# 'Jahi':76,
# 'Kabusa':77,
# 'Kado':78,
# 'Kaduna North':79,
# 'Kaduna South':80,
# 'Kafe':81,
# 'Karmo':82,
# 'Karsana':83,
# 'Karu':84,
# 'Katampe':85,
# 'Kaura':86,
# 'Keffi':87,
# 'Ketu':88,
# 'Kosofe':89,
# 'Kubwa':90,
# 'Kuje':91,
# 'Kukwaba':92,
# 'Kurudu':93,
# 'Lagos Island':94,
# 'Lekki':95,
# 'Life Camp':96,
# 'Lokogoma District':97,
# 'Lugbe District':98,
# 'Mabushi':99,
# 'Magboro':100,
# 'Magodo':101,
# 'Maitama District':102,
# 'Maryland':103,
# 'Mbora (Nbora)':104,
# 'Mowe Ofada':105,
# 'Mowe Town':106,
# 'Mpape':107,
# 'Mushin':108,
# 'Obio-Akpor':109,
# 'Ogudu':110,
# 'Ojo':111,
# 'Ojodu':112,
# 'Ojota':113,
# 'Oke-Aro':114,
# 'Okene':115,
# 'Oluyole':116,
# 'Oredo':117,
# 'Orozo':118,
# 'Oshodi':119,
# 'Osogbo':120,
# 'Owerri Municipal':121,
# 'Owerri North':122,
# 'Owerri West':123,
# 'Paikoro':124,
# 'Port Harcourt':125,
# 'Sango Ota':126,
# 'Shomolu':127,
# 'Simawa':128,
# 'Surulere':129,
# 'Udu':130,
# 'Ughelli South':131,
# 'Uhunmwonde':132,
# 'Umuahia':133,
# 'Utako':134,
# 'Uyo':135,
# 'Victoria Island (VI)':136,
# 'Warri':137,
# 'Wumba':138,
# 'Wuse':139,
# 'Wuse 2':140,
# 'Wuye':141,
# 'Yaba':142,
# 'Yenagoa':143,}
#     def decode_town(encoded_town: int) -> str:
#         reverse_town_map = {v: k for k, v in town_map.items()}
#         return reverse_town_map.get(encoded_town, "Unknown Town")
#     return{
#         "message":  decode_town(3),
#         "rand": 12
#     }